version: '3.1'

services:
  nextjs:
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
